apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: java-springboot-fumvbmhj 
  janus-idp.io/tekton: java-springboot-fumvbmhj
  backstage.io/kubernetes-id: java-springboot-fumvbmhj
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: java-springboot-fumvbmhj
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml